sudo: false
language: cpp

compiler:
  - gcc

# Make sure cmake picks up the compiler we want
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - wget http://root.cern.ch/download/root_v5.34.30.source.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.source.tar.gz
  - mv root root-src
  - wget http://root.cern.ch/download/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - source ./root/bin/thisroot.sh
  - root-config --libs
  - root-config --cflags
    # Move some ROOT header files to common include directory
  - rsync -auv root-src/math/mathmore/inc/Math root/include/
  - git clone --depth=1 https://github.com/star-bnl/star-base.git    ext/star-base
  - git clone --depth=1 https://github.com/star-bnl/star-stevent.git ext/star-stevent
  - git clone --depth=1 https://github.com/star-bnl/star-sim.git     ext/star-sim
  - git clone --depth=1 https://github.com/star-bnl/star-tables.git  ext/star-tables
  - git clone --depth=1 https://github.com/star-bnl/star-emc.git     ext/star-emc
  - git clone --depth=1 https://github.com/star-bnl/star-daq.git     ext/star-daq
  - git clone --depth=1 https://github.com/star-bnl/star-fgt.git     ext/star-fgt
  - git clone --depth=1 https://github.com/star-bnl/star-pams.git    ext/star-pams

branches:
  only:
    - master

script:
  - mkdir build/ && cd build/
  - cmake -D CMAKE_CXX_FLAGS=-std=c++0x -D STAR_BASE_DIR=ext/star-base -D STAR_STEVENT_DIR=ext/star-stevent -D STAR_SIM_DIR=ext/star-sim -D STAR_TABLES_DIR=ext/star-tables -D STAR_EMC_DIR=ext/star-emc -D STAR_DAQ_DIR=ext/star-daq -D STAR_FGT_DIR=ext/star-fgt -D STAR_PAMS_DIR=ext/star-pams ../
  - cmake -DCMAKE_INSTALL_PREFIX=./ ../
  - make -j4
  - make install
  - pwd && ls -la . && ls -la lib/
